steps:
  - label: Plan Dev
    commands:
      - bash ./tg-plan.sh dev
    artifact_paths:
      - "dev/.terragrunt-cache/**/*"
      - "dev/terraform.tfplan"

  - label: Plan Live
    commands: 
      - bash ./tg-plan.sh live
    artifact_paths:
      - "live/.terragrunt-cache/**/*"
      - "live/terraform.tfplan"

  - wait

  - label: Apply Dev
    commands:
      - buildkite-agent artifact download "dev/**/*" "dev"
      - bash ./tg-apply.sh dev

  - wait

  - label: Apply Live
    commands: 
      - buildkite-agent artifact download "live/**/*" "live"
      - bash ./tg-apply.sh live
