steps:
  - label: Plan Dev
    commands:
      - bash ./deploy/scripts/plan.sh dev
    artifact_paths:
      - "deploy/environments/dev/terraform.tfplan"
      - "lambda.zip"

  - label: Plan Live
    commands: 
      - bash ./deploy/scripts/plan.sh live
    artifact_paths:
      - "deploy/environments/live/terraform.tfplan"
      - "lambda.zip"

  - wait

  - label: Apply Dev
    commands:
      - buildkite-agent artifact download "deploy/environments/dev/terraform.tfplan" "deploy/environments/dev"
      - buildkite-agent artifact download "lambda.zip" . --step "Plan Dev"
      - bash ./apply.sh dev

  - wait

  - label: Apply Live
    commands: 
      - buildkite-agent artifact download "deploy/environments/live/terraform.tfplan" "deploy/environments/live"
      - buildkite-agent artifact download "lambda.zip" . --step "Plan Live"
      - bash ./apply.sh live
